Add `alias` argument to `deduplicate` macro
dbt-labs/dbt-utils pull request #526
Opened 2022-03-22 08:51 UTC by judahrand

This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [x] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation

It occurred to me that quite often one might want to first filter a model and then deduplicate it. The requirement for `deduplicate` to take a relation makes this difficult. By adding an `alias` argument we allow the macro to find the columns from a relation but to select from a CTE.

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [x] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [x] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
    - [x] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [x] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` instead of `TIMESTAMP`
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

2022-03-22 08:54 UTC, judahrand commented
@joellabes I didn't add these changes to the original PR as it seemed like an additional enhancement to me. Would you be happy for these changes to go in too?

2022-03-23 03:33 UTC, joellabes requested changes
I like it! My only request is that we call it `relation_alias`, so that its interface aligns with the star macro which has similar behaviour. Just makes it easier for people to guess the correct argument name without checking the docs, if they already know the concept from a different macro.

2022-03-23 09:10 UTC, judahrand commented
> I like it! My only request is that we call it `relation_alias`, so that its interface aligns with the star macro which has similar behaviour. Just makes it easier for people to guess the correct argument name without checking the docs, if they already know the concept from a different macro.

I had considered this initially but felt like the argument is quite different to the `relation_alias` arg of `star`, however, if you think this is better I'm happy to go with it!

2022-03-25 03:52 UTC, joellabes commented
Yeah it's not _exactly_ the same, but I think it still works! Thanks for your contribution ⭐

2022-03-25 03:52 UTC, joellabes approved these changes

2022-03-25 03:52 UTC, merged