Remove extraneous whitespace
dbt-labs/dbt-utils pull request #529
Opened 2022-03-25 15:22 UTC by SunriseLong

This is a:
- [x ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [ ] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [ ] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` instead of `TIMESTAMP`
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

2022-03-28 04:07 UTC, joellabes requested changes
Hi @SunriseLong, thank you for doing this! These look good, a couple of nitpicks but I'm very excited to get this in! Thanks for providing the before/after examples, made it super easy to see what had changed 🙏

2022-03-28 04:07 UTC, joellabes commented on macros/cross_db_utils/datediff.sql
> +{%- macro default__datediff(first_date, second_date, datepart) -%}
The leading `-` doesn't do anything (there is no whitespace prior to it to remove) - this is also true for the trailing `-` in the `endmacro` block, but I haven't added this suggestion in every place
```suggestion
{% macro default__datediff(first_date, second_date, datepart) -%}
```

2022-03-28 04:07 UTC, joellabes commented on macros/cross_db_utils/date_trunc.sql
>  {% macro bigquery__date_trunc(datepart, date) %}
For cross-db support, you'll need to do the same thing on each of the adapter-specific macros, like this: 

```suggestion
{% macro bigquery__date_trunc(datepart, date) -%}
```

Again, I haven't applied this _everywhere_ it's necessary - just one example

2022-03-28 16:08 UTC, SunriseLong commented
Thanks addressed. The `redshift__datediff()` whitespace control is a little redundant since it returns `default__datediff()` which is already controlled.

Haven't tested the gcp adapters btw

2022-03-29 03:56 UTC, joellabes submitted a review, later dismissed

2022-03-29 03:57 UTC, joellabes commented
This is looking great! The integration tests exercise BigQuery (as well as Snowflake, Redshift and Postgres) so we should be OK on GCP 👍 

Going to change the base branch to `next/patch` which might cause some chaos, but otherwise this is good to merge! Thanks for your contribution 💟

2022-03-29 03:59 UTC, joellabes approved these changes

2022-03-29 04:03 UTC, merged