Feature/add where to unique combination of columns
dbt-labs/dbt-utils pull request #612
Opened 2022-06-21 20:04 UTC by epapineau

This is a:
- [ ] documentation update
- [ ] bug fix with no breaking changes
- [ ] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [ ] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` instead of `TIMESTAMP`
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

2022-06-21 22:03 UTC, dbeatty10 requested changes
This looks great, @epapineau 🥇 

One of the trickiest things is adding a new section to the top of the CHANGELOG for the first merge after a release.

Could you add the following to the top of CHANGELOG.md and move your two additions into that new section?

It will end up looking something like this:

```md
<!--- Copy, paste, and uncomment the following headers as-needed for unreleased features
# Unreleased
## New features
- XXX ([#XXX](https://github.com/dbt-labs/dbt-utils/issues/XXX), [#XXX](https://github.com/dbt-labs/dbt-utils/pull/XXX))
## Fixes
## Quality of life
## Under the hood
## Contributors:
--->

# Unreleased

## New features
- New `where` clause parameter to `unique_combination_of_columns` test to filter values tested ([#612](https://github.com/dbt-labs/dbt-utils/pull/612))

## Contributors:
- [@epapineau](https://github.com/epapineau) (#612)

# dbt-utils v0.8.6
...
```

We'll want to restore your entry within 0.8.6 too:
```md
- [@epapineau](https://github.com/epapineau) (#583)
```

2022-06-21 22:19 UTC, epapineau commented
@dbeatty10 thanks for the feedback. I updated the changelog including correcting [I think] the PR# for 0.8.6

2022-06-22 15:34 UTC, dbeatty10 requested changes

2022-06-24 00:24 UTC, epapineau commented on integration_tests/models/generic_tests/schema.yml
> +
Ohh good catch, thank you!! I've made the requested changes + added a test confirming the test also fails when it should

2022-07-15 15:51 UTC, dbeatty10 approved these changes
This looks awesome to me, @epapineau 🏆 

Would you be willing to give this a looksie too @joellabes ?

2022-07-18 02:01 UTC, joellabes commented
the code itself LGTM! my only comment is that given that all tests [get `where` for free](https://docs.getdbt.com/reference/resource-configs/where), how does this differ? is it filtering earlier than the native where or something?

2022-08-04 00:31 UTC, epapineau commented
@joellabes I think you're right - I didn't realize that config extended beyond the dbt core tests. Should I close the issue?

2022-08-04 20:49 UTC, joellabes commented
I think so yeah!

2022-08-04 20:49 UTC, closed without merging