Feature: Add option to remove the source_column_name on the union_relations macro
dbt-labs/dbt-utils pull request #624
Opened 2022-07-21 17:10 UTC by christineberger

This is a:
- [ ] documentation update
- [ ] bug fix with no breaking changes
- [x] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation

This covers issue #331, which allows passing in `none` in order to omit a `source_column_name` column when unioning.

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [ ] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` instead of `TIMESTAMP`
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

2022-07-25 04:29 UTC, joellabes requested changes
I love it 😻 thank you for doing this! For integration tests, ~you can follow the same pattern as the existing union relations tests:~ update: this is good advice for testing in general, but not in this case! see below

- make a model that calls `union_relations` but passes `None` as the column name, like [this one](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/models/sql/test_union_base.sql)
- Make a seed file for the expected output, like [this one](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/data/sql/data_union_expected.csv)
- Add an equality test [like this](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/models/sql/schema.yml#L151-L154)

So here's a fun thing I found while building this list! We actually are already [dropping the column in our testing](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/models/sql/test_union.sql). The commit message implies that it's because the tables change depending on the environment which makes sense! 

Perhaps what you do instead is run a test that validates the columns that you expect are there, but don't worry about actually testing the union itself. You could do that either by making an empty seed file and comparing that to a [`{{ limit_zero() }}`'d](https://github.com/dbt-labs/dbt-utils/blob/73a65562bf3d9b31a1eca0b27118056ad048d8fc/integration_tests/macros/limit_zero.sql) version of the table, or by using dbt-expectations' [expect_table_columns_to_match_ordered_list](https://github.com/calogica/dbt-expectations#expect_table_columns_to_match_ordered_list)

2022-07-25 04:29 UTC, joellabes commented on README.md
> +be used to omit this column.
A bit concerned that using a colon might make people think that's how you pass the argument. (As I type this, I'm suddenly paranoid that you can use colons as well as equals signs 😱)

```suggestion
the column that records the source of this row. Pass `None` to omit this column from the results.
```

2022-07-26 21:22 UTC, christineberger commented
@joellabes I committed your suggestion and also added integration tests! Requested re-review. 😊

2022-07-26 22:56 UTC, joellabes approved these changes
outstanding! thank you ⭐ i'll commit the typo fix on your behalf and then get this merged!

2022-07-26 22:56 UTC, joellabes commented on integration_tests/tests/generic/expect_table_columns_to_match_set.sql
> +    {# Replaces dbt_exoectations._list_intersect() #}
```suggestion
    {# Replaces dbt_expectations._list_intersect() #}
```

2022-07-26 22:57 UTC, merged