add generate_surrogate_key macro
dbt-labs/dbt-utils pull request #685
Opened 2022-09-23 21:05 UTC by dave-connors-3

resolves #488 

This is a:
- [ ] documentation update
- [x] bug fix with no breaking changes
- [x] new functionality
- [x] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation

This PR is a breaking change for users of the `surrogate_key` macro -- `dbt_utils.surrogate_key` now throws a compilation error, and the `generate_surrogate_key` macro uses a default value for the coalesce function of `_dbt_utils_surrogate_key_null_` to disambiguate from empty string values. 

Parity can be achieved by adding a boolean variable to your dbt project:

```yml
# dbt_project.yml
...
vars:
  dbt_utils:
    surrogate_key_treat_nulls_as_empty_strings: True
```

## Checklist
- [x] This code is associated with an Issue which has been triaged and [accepted for development](https://docs.getdbt.com/docs/contributing/oss-expectations#pull-requests). 
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [x] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [x] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt.type_*` macros instead of explicit datatypes (e.g. `dbt.type_timestamp()` instead of `TIMESTAMP`
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

2022-09-26 21:46 UTC, dave-connors-3 commented
@joellabes -- assuming tests pass here I think we're in decent shape -- decided not to take the handling for non-list args into the new world of `generate_surrogate_key` -- if we're breaking everyone's project, we might as well break it for the better

2022-09-28 02:51 UTC, joellabes requested changes
This is wonderful! Thank you @dave-connors-3. In the interest of getting the next beta out, I'm going to accept my suggestions and merge this, but if you want to make any changes then there will be another beta release before GA I'm sure!

2022-09-28 02:51 UTC, joellabes commented on macros/sql/generate_surrogate_key.sql
> +    {%- endif -%}
The modern way to do this is to use `do`: 
```suggestion
    {%- do fields.append(
        "coalesce(cast(" ~ field ~ " as " ~ type_string() ~ "), '" ~ default_null_value  ~"')"
    ) -%}

    {%- if not loop.last %}
        {%- do fields.append("'-'") -%}
    {%- endif -%}
```

2022-09-28 02:51 UTC, joellabes commented on macros/sql/surrogate_key.sql
> +The {}.{} model triggered this warning. \
```suggestion
Warning: `dbt_utils.surrogate_key` has been replaced by \
`dbt_utils.generate_surrogate_key`. The new macro treats null values \
differently to empty strings. To restore the behaviour of the original \
macro, add a variable scoped to the dbt_utils package called \
`surrogate_key_treat_nulls_as_empty_strings` to your \
dbt_project.yml file with a value of True. \
The {}.{} model triggered this warning. \
```

Tweaked the wording. Eyeballed the alignment in the GitHub UI so it's probably not 80 chars exactly or whatever number you were going for.

2022-09-28 03:05 UTC, joellabes approved these changes
🤩 😍

2022-09-28 03:19 UTC, merged