Equality exclude columns
dbt-labs/dbt-utils pull request #829
Opened 2023-08-30 16:47 UTC by seub

resolves #828 

This is a:
- [ ] documentation update
- [ ] bug fix with no breaking changes
- [x] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation

This PR adds an optional `exclude_columns` to the `equality` test (similar to `compare_columns`).

## Checklist
- [ ] This code is associated with an Issue which has been triaged and [accepted for development](https://docs.getdbt.com/docs/contributing/oss-expectations#pull-requests). 
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [x] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [x] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt.type_*` macros instead of explicit datatypes (e.g. `dbt.type_timestamp()` instead of `TIMESTAMP`
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

2023-08-30 22:39 UTC, seub commented
Update: I figured out what the deal was with Snowflake and quoted columns. I fixed it with a new version that is a bit uglier but seems to work. However it's now failing for BigQuery apparently. Some help would be great 🙏

2023-08-31 16:58 UTC, seub commented
Update: I think I finally figured out how to handle quoting in a satisfactory way (tricky! But I learned something).

I think the PR is good to go! Thanks for reviewing 🙏

2023-09-20 01:08 UTC, joellabes requested changes
At a glance this looks good! One note is that only one of `compare_columns` and `exclude_columns` should be accepted (see [union_relations](https://github.com/dbt-labs/dbt-utils#union_relations-source) for an example)

I'll try and find someone for a more robust review and getting this merged 🎉

2023-09-20 14:24 UTC, seub commented
Thank you @joellabes !

About forbidding to have both `compare_columns` and `exclude_columns`: I considered that; I also saw an example of that in the macro `get_merge_update_columns` in dbt-core [here](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/incremental/column_helpers.sql).

We could easily forbid it explicitly, but imho there's no need. The final set of columns that will be compared is the subset of `compare_columns` that are not in `exclude_columns`, that seems pretty natural.

2023-09-25 14:50 UTC, rlh1994 commented
I think this is a duplicate of https://github.com/dbt-labs/dbt-utils/pull/765 (although that uses `ignore_columns`, no particular reason)?

2023-10-24 13:52 UTC, seub commented
@rlh1994 Sorry for the slow response!

Indeed it is duplicate, my bad for missing it. Do you know what's the hold up with your PR? Looks like it's been open for more than 6 months.

If I compare what I wrote to your PR, I only see 2 tiny differences:
- Terminology: I went for `exclude_columns` instead of your `ignore_columns`. Either is perfectly reasonable, I went for `exclude` to mimic the `merge_exclude_columns` in dbt-core.
- My PR allows to have both `compare_columns` and `exclude_columns`. I don't think it hurts to allow both, but it also makes sense to not allow it.

I tried to be very careful about quoting (depending on whether `compare_columns` is provided) and I think my PR works. I was pleased to see that your logic does exactly the same as mine. I use `get_quoted_csv` in one case and you don't but the result is the same.

I'm looking forward to your PR being merged and I can close this one. Unless you want to split yours to only add `precision`? I don't think it's worth it, unless something about that is holding up your PR from being approved?

2023-10-24 18:05 UTC, rlh1994 commented
@seub I think `exclude_columns` makes more sense, I'll swap mine over to that. Mine also additionally checks if one of the tables is missing one of the columns (which was previously missed in one direction, I can't remember which).

I don't know of any reasons the PR isn't progressing tbh, I think it's ready to go but just awaiting a review

2024-04-22 12:50 UTC, dbeatty10 commented
Thank you @seub and @rlh1994 !

Closing this in favor of https://github.com/dbt-labs/dbt-utils/pull/765

2024-04-22 12:50 UTC, closed without merging